# CI is organized into stages so that if early stages fail
# the later ones are not run.
stages:
  # Initial test build for checking simple compilation and getting regressiontest repo
  - pre-build
  # Configuration for building and testing
  - configure-build
  # Build GROMACS in multiple configurations
  - build
  # Test each configuration, perhaps in multiple ways
  - test
  # Generate documentation files
  - documentation
  # Check documentation from source code for errors
  - source-check
  # Linting, docs, static analysis, coverage, code analysis...
  - post-test
  # Nightly work to configure builds
  - nightly-configure
  # Nightly build stage
  - nightly-build
  # Nightly deploy stage
  - nightly-deploy
  # Release work for packaging code
  - release-package
  # Release checksum verification
  - release-verify
  # Configure code for release builds
  - release-configure
  # Release work for packaging code
  - release-build
  # Tests for release code
  - release-tests
  # Prepare for deploying artifacts
  - release-prepare-deploy
  # Deploy stage for release builds
  - release-deploy

default:
  tags:
    - k8s-scilifelab

include:
  # Mix-in helper job definitions of general utility.
  - local: '/admin/gitlab-ci/global.gitlab-ci.yml'
  # Various composable job definitions.
  - local: '/admin/ci-templates/.build-template.yml'
  - local: '/admin/ci-templates/.gcc-before-script.yml'
  - local: '/admin/ci-templates/.gcc-build-template.yml'
  - local: '/admin/ci-templates/.gcc-test-template.yml'
  - local: '/admin/ci-templates/.clang-build-template.yml'
  - local: '/admin/ci-templates/.clang-test-template.yml'
  - local: '/admin/ci-templates/.clang-before-script.yml'
  - local: '/admin/ci-templates/.cuda-template.yml'
  - local: '/admin/ci-templates/.build-gmxapi-template.yml'
  # Build and test in a variety of environments and configurations.
  # To do: expand matrix here to improve transparency and reduce file sizes.
  # E.g. '/admin/gitlab-ci/matrix/clang-8.gitlab-ci.yml
  - local: '/admin/gitlab-ci/testing-matrix.gitlab-ci.yml'
  # Repository cleanliness. Source tidiness, linting, and policy compliance.
  - local: '/admin/gitlab-ci/lint.gitlab-ci.yml'
  # Web page and manual.
  - local: '/admin/gitlab-ci/documentation.gitlab-ci.yml'
  # Prepare release archives.
  - local: '/admin/gitlab-ci/archive.gitlab-ci.yml'
