.variables:default:
  variables:
    KUBERNETES_CPU_LIMIT: 8
    KUBERNETES_CPU_REQUEST: 4
    KUBERNETES_MEMORY_LIMIT: 8Gi
    KUBERNETES_EXTENDED_RESOURCE_NAME: ""
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 0
    CACHE_FALLBACK_KEY: "$CI_JOB_NAME-$CI_JOB_STAGE-master"
    BUILD_DIR: build
    INSTALL_DIR: install

.build-cache-template:
  cache:
    key: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      - ccache/

.pull-cache-template:
  cache:
    key: "$CI_JOB_NAME-$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    # Read but don't update the cache
    policy: pull

.no-cache-template:
  cache: {}


# Tool chains
.gcc5-template:
  image: gromacs/ci-gcc-5:master

.gcc6-template:
  image: gromacs/ci-gcc-6:master

.gcc7-template:
  image: gromacs/ci-gcc-7:master

.gcc8-template:
  image: gromacs/ci-gcc-8:master

.clang6-template:
  image: gromacs/ci-clang-6:master

.clang7-template:
  image: gromacs/ci-clang-7:master

.clang8-template:
  image: gromacs/ci-clang-8:master

.gcc5-gmxapi-template:
  image: gromacs/ci-gcc-5-gmxapi:master

.gcc6-gmxapi-template:
  image: gromacs/ci-gcc-6-gmxapi:master

.gcc7-gmxapi-template:
  image: gromacs/ci-gcc-7-gmxapi:master

.gcc8-gmxapi-template:
  image: gromacs/ci-gcc-8-gmxapi:master

.clang6-gmxapi-template:
  image: gromacs/ci-clang-6-gmxapi:master

.clang7-gmxapi-template:
  image: gromacs/ci-clang-7-gmxapi:master

.clang8-gmxapi-template:
  image: gromacs/ci-clang-8-gmxapi:master

.gcc-8-cuda-10.2-template:
  image: gromacs/ci-gcc-8-cuda-10.2:master
  variables:
    CUDA_BASE_VERSION: "10.2"
    COMPILER_MAJOR_VERSION: 8

