# Packages, exported artifacts, and release engineering processes.

# Jobs running in release stage
linkchecker:
  extends:
    - .build-docs-webpage
  stage: nightly-build
  dependencies:
    - webpage-gmxapi
  only:
    - schedules
    - triggers
    - merge_requests
    - external_pull_requests
  except:
    variables:
      - $GROMACS_RELEASE
  variables:
    KUBERNETES_CPU_LIMIT: 1
    KUBERNETES_CPU_REQUEST: 1
    KUBERNETES_MEMORY_LIMIT: 2Gi
    BUILD_DIR: build-docs-gmxapi
  script:
    - cd $BUILD_DIR
    - linkchecker docs/html/index.html -f ../docs/linkcheckerrc -Fxml --ignore-url html-full
      --ignore-url html-user --ignore-url html-lib --ignore-url .tar.gz --ignore-url _sources
      -o xml
  artifacts:
    reports:
      junit: $BUILD_DIR/linkchecker-out.xml

build-archive-nightly:
  extends:
    - .build-archive
  stage: nightly-build
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-archive-nightly
      artifacts: true
  only:
    - triggers
    - schedules
  except:
    variables:
      - $GROMACS_RELEASE
  variables:
    BUILD_DIR: build-package

package-regressiontests-release:
  extends:
    - .regressiontests-extends-template
    - .regressiontests-release-template
  needs:
    - job: prepare-release-version
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE


package-archive-release:
  extends:
    - .build-archive
  stage: release-package
  needs:
    - job: configure-archive-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE
  variables:
    BUILD_DIR: build-package

release-verify:
  extends:
    - .regressiontests-extends-template
    - .release-verify-template
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-7-release:
  extends:
    - .configure-gcc-release
    - .no-cache-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-7-gmxapi-release:
  extends:
    - .configure-gcc-release
    - .configure-gmxapi-template
    - .no-cache-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-7-double-release:
  extends:
    - .configure-gcc-release
    - .no-cache-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    CMAKE_PRECISION_OPTIONS: -DGMX_DOUBLE=ON
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-8-release:
  extends:
    - .configure-gcc-release
    - .no-cache-template
    - .gcc8-template
  variables:
    COMPILER_MAJOR_VERSION: 8
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-clang-7-release:
  extends:
    - .configure-clang-release
    - .no-cache-template
    - .clang7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-clang
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-clang-7-gmxapi-release:
  extends:
    - .configure-clang-release
    - .configure-gmxapi-template
    - .no-cache-template
    - .clang7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-clang
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-clang-8-release:
  extends:
    - .configure-clang-release
    - .no-cache-template
    - .clang8-template
  variables:
    COMPILER_MAJOR_VERSION: 8
    RELEASE_BUILD_DIR: release-builds-clang
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

build-gcc-7-release:
  extends:
    - .build-gcc
    - .gcc7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-7-gmxapi-release:
  extends:
    - .build-gcc
    - .gmxapi-extra-installs
    - .gcc7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-7-double-release:
  extends:
    - .build-gcc
    - .gcc7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-double-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-8-release:
  extends:
    - .build-gcc
    - .gcc8-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-8-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-clang-7-release:
  extends:
    - .build-clang
    - .clang7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-clang-7-gmxapi-release:
  extends:
    - .build-clang
    - .gmxapi-extra-installs
    - .clang7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-clang-8-release:
  extends:
    - .build-clang
    - .clang8-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-8-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

test-gcc-7-release:
  extends:
    - .test-gcc
    - .gcc7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-release
      artifacts: true
    - job: build-gcc-7-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-7-gmxapi-release:
  extends:
    - .test-gcc
    - .gmxapi-extra-installs
    - .gcc7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-gmxapi-release
      artifacts: true
    - job: build-gcc-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-7-double-release:
  extends:
    - .test-gcc
    - .gcc7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-double-release
      artifacts: true
    - job: build-gcc-7-double-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-8-release:
  extends:
    - .test-gcc
    - .gcc8-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-8-release
      artifacts: true
    - job: build-gcc-8-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-clang-7-release:
  extends:
    - .test-clang
    - .clang7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-release
      artifacts: true
    - job: build-clang-7-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-clang-7-gmxapi-release:
  extends:
    - .test-clang
    - .gmxapi-extra-installs
    - .clang7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-gmxapi-release
      artifacts: true
    - job: build-clang-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-clang-8-release:
  extends:
    - .test-clang
    - .clang8-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-8-release
      artifacts: true
    - job: build-clang-8-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE
