# Initial build that always needs to pass before follow-up stages run
simple-build:
  extends:
    - .simple-build-template
    - .build-cache-template
    - .variables:default
    - .gcc-before-script-template
    - .build-gcc-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    BUILD_DIR: simple-build
  except:
    variables:
      - $GROMACS_RELEASE

# Jobs running in first pre-build stage

.configure-extends-template:
  extends:
    - .configure-build-template
    - .no-cache-template
    - .variables:default

.configure-release-extends-template:
  extends:
    - .configure-build-release-template
    - .no-cache-template
    - .variables:default

# Templates for configuration stage
.configure-gcc:
  extends:
    - .configure-extends-template
    - .gcc-before-script-template
    - .build-gcc-template

.configure-gcc-release:
  extends:
    - .configure-release-extends-template
    - .gcc-before-script-template
    - .build-gcc-template

.configure-gcc-cuda:
  extends:
    - .configure-gcc
    - .cuda-template

configure-gcc-7:
  extends:
    - .configure-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 7
  except:
    variables:
      - $GROMACS_RELEASE

configure-gcc-7-release:
  extends:
    - .configure-gcc-release
    - .no-cache-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-7-simd-sse41:
  extends:
    - .configure-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 7
    CMAKE_SIMD_OPTIONS: "-DGMX_SIMD=SSE4.1"
  except:
    variables:
      - $GROMACS_RELEASE

configure-gcc-7-double:
  extends:
    - .configure-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 7
    CMAKE_PRECISION_OPTIONS: -DGMX_DOUBLE=ON
  except:
    variables:
      - $GROMACS_RELEASE

configure-gcc-7-double-release:
  extends:
    - .configure-gcc-release
    - .no-cache-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    CMAKE_PRECISION_OPTIONS: -DGMX_DOUBLE=ON
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-7-gmxapi:
  extends:
    - .configure-gcc
    - .configure-gmxapi-template
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 7
  except:
    variables:
      - $GROMACS_RELEASE

configure-gcc-7-gmxapi-release:
  extends:
    - .configure-gcc-release
    - .configure-gmxapi-template
    - .no-cache-template
    - .gcc7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-8:
  extends:
    - .configure-gcc
    - .gcc8-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 8
  except:
    variables:
      - $GROMACS_RELEASE

configure-gcc-8-release:
  extends:
    - .configure-gcc-release
    - .no-cache-template
    - .gcc8-template
  variables:
    COMPILER_MAJOR_VERSION: 8
    RELEASE_BUILD_DIR: release-builds-gcc
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-gcc-8-cuda-10.2:
  extends:
    - .configure-gcc-cuda
    - .gcc-8-cuda-10.2-template
  needs:
    - job: simple-build
      artifacts: false
  except:
    variables:
      - $GROMACS_RELEASE

.configure-clang:
  extends:
    - .configure-extends-template
    - .clang-before-script-template
    - .build-clang-template

.configure-clang-release:
  extends:
    - .configure-release-extends-template
    - .clang-before-script-template
    - .build-clang-template

# For version of clang before 7, we need to always provide the full version
# Use something like this instead in the download script:
# APT_COMPILER_VERSION=$(($COMPILER_MAJOR_VERSION < 7 ? "${COMPILER_MAJOR_VERSION}.0" : $COMPILER_MAJOR_VERSION))
configure-clang-6:
  extends:
    - .configure-clang
    - .clang6-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: "6.0"
    CMAKE_MPI_OPTIONS: -DGMX_OPENMP=OFF
  except:
    variables:
      - $GROMACS_RELEASE

configure-clang-7:
  extends:
    - .configure-clang
    - .clang7-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 7
  except:
    variables:
      - $GROMACS_RELEASE

configure-clang-7-release:
  extends:
    - .configure-clang-release
    - .no-cache-template
    - .clang7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-clang
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-clang-7-gmxapi:
  extends:
    - .configure-clang
    - .configure-gmxapi-template
    - .clang7-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 7
  except:
    variables:
      - $GROMACS_RELEASE

configure-clang-7-gmxapi-release:
  extends:
    - .configure-clang-release
    - .configure-gmxapi-template
    - .no-cache-template
    - .clang7-template
  variables:
    COMPILER_MAJOR_VERSION: 7
    RELEASE_BUILD_DIR: release-builds-clang
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

configure-clang-8:
  extends:
    - .configure-clang
    - .clang8-template
  needs:
    - job: simple-build
      artifacts: false
  variables:
    COMPILER_MAJOR_VERSION: 8
  except:
    variables:
      - $GROMACS_RELEASE

configure-clang-8-release:
  extends:
    - .configure-clang-release
    - .no-cache-template
    - .clang8-template
  variables:
    COMPILER_MAJOR_VERSION: 8
    RELEASE_BUILD_DIR: release-builds-clang
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE
  dependencies:
    - package-archive-release
    - package-regressiontests-release
    - prepare-release-version

# Jobs running during build stage

.build-extends-template:
  extends:
    - .binary-build-template
    - .build-cache-template
    - .variables:default

.build-gcc:
  extends:
    - .build-extends-template
    - .gcc-before-script-template
    - .build-gcc-template

.build-gcc-cuda:
  extends:
    - .build-gcc
    - .cuda-template

build-gcc-7:
  extends:
    - .build-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-gcc-7
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-gcc-7-release:
  extends:
    - .build-gcc
    - .gcc7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-7-simd-sse41:
  extends:
    - .build-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-gcc-7-simd-sse41
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-gcc-7-double:
  extends:
    - .build-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-gcc-7-double
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-gcc-7-gmxapi:
  extends:
    - .build-gcc
    - .gmxapi-extra-installs
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-gcc-7-gmxapi
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-gcc-7-double-release:
  extends:
    - .build-gcc
    - .gcc7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-double-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-7-gmxapi-release:
  extends:
    - .build-gcc
    - .gmxapi-extra-installs
    - .gcc7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-8:
  extends:
    - .build-gcc
    - .gcc8-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-gcc-8
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-gcc-8-release:
  extends:
    - .build-gcc
    - .gcc8-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-8-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-gcc-8-cuda-10.2:
  extends:
    - .build-gcc-cuda
    - .gcc-8-cuda-10.2-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-gcc-8-cuda-10.2
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

.build-clang:
  extends:
    - .build-extends-template
    - .clang-before-script-template
    - .build-clang-template

build-clang-6:
  extends:
    - .build-clang
    - .clang6-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-clang-6
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-clang-7:
  extends:
    - .build-clang
    - .clang7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-clang-7
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-clang-7-release:
  extends:
    - .build-clang
    - .clang7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-clang-7-gmxapi:
  extends:
    - .build-clang
    - .gmxapi-extra-installs
    - .clang7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-clang-7-gmxapi
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-clang-7-gmxapi-release:
  extends:
    - .build-clang
    - .gmxapi-extra-installs
    - .clang7-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE

build-clang-8:
  extends:
    - .build-clang
    - .clang8-template
  needs:
    - job: simple-build
      artifacts: false
    - job: configure-clang-8
      artifacts: true
  except:
    variables:
      - $GROMACS_RELEASE

build-clang-8-release:
  extends:
    - .build-clang
    - .clang8-template
  stage: release-build
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-8-release
      artifacts: true
  only:
    refs:
      - web
      - schedules
      - triggers
    variables:
      - $GROMACS_RELEASE


# Jobs running during test stage
.test-script-template:
  script:
    - cd $BUILD_DIR
    - ctest -D ExperimentalTest --output-on-failure | tee ctestLog.log || true
    - awk '/The following tests FAILED/,/^Errors while running CTest|^$/'
      ctestLog.log | tee ctestErrors.log
    - xsltproc scripts/CTest2JUnit.xsl Testing/`head -n 1 < Testing/TAG`/Test.xml > JUnitTestResults.xml
    - if [ -s ctestErrors.log ] ; then
      echo "Error during running ctest";
      exit 1;
      fi
    - cd ..
  artifacts:
    reports:
      junit: $BUILD_DIR/JUnitTestResults.xml
    paths:
      - $BUILD_DIR/Testing
      - $BUILD_DIR/tests
    when: always
    expire_in: 1 week

.test-extends-template:
  extends:
    - .test-base-template
    - .pull-cache-template
    - .test-script-template
    - .variables:default

# Templates for test stage
.test-gcc:
  extends:
    - .test-extends-template
    - .gcc-before-script-template
    - .test-gcc-template

.test-gcc-cuda:
  extends:
    - .test-gcc
    - .cuda-template

test-gcc-7:
  extends:
    - .test-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-gcc-7
  except:
    variables:
      - $GROMACS_RELEASE

test-gcc-7-release:
  extends:
    - .test-gcc
    - .gcc7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-release
      artifacts: true
    - job: build-gcc-7-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-7-simd-sse41:
  extends:
    - .test-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-gcc-7-simd-sse41
  except:
    variables:
      - $GROMACS_RELEASE

test-gcc-7-double:
  extends:
    - .test-gcc
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-gcc-7-double
  except:
    variables:
      - $GROMACS_RELEASE

test-gcc-7-double-release:
  extends:
    - .test-gcc
    - .gcc7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-double-release
      artifacts: true
    - job: build-gcc-7-double-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-7-gmxapi:
  extends:
    - .test-gcc
    - .gmxapi-extra-installs
    - .gcc7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-gcc-7-gmxapi
  except:
    variables:
      - $GROMACS_RELEASE

test-gcc-7-gmxapi-release:
  extends:
    - .test-gcc
    - .gmxapi-extra-installs
    - .gcc7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-7-gmxapi-release
      artifacts: true
    - job: build-gcc-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-8:
  extends:
    - .test-gcc
    - .gcc8-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-gcc-8
  except:
    variables:
      - $GROMACS_RELEASE

test-gcc-8-release:
  extends:
    - .test-gcc
    - .gcc8-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-gcc
  needs:
    - job: configure-gcc-8-release
      artifacts: true
    - job: build-gcc-8-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-gcc-8-cuda-10.2:
  variables:
    KUBERNETES_EXTENDED_RESOURCE_NAME: "nvidia.com/gpu"
    KUBERNETES_EXTENDED_RESOURCE_LIMIT: 1
  extends:
    - .test-gcc-cuda
    - .gcc-8-cuda-10.2-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-gcc-8-cuda-10.2
  except:
    variables:
      - $GROMACS_RELEASE

.test-clang:
  extends:
    - .test-extends-template
    - .clang-before-script-template
    - .test-clang-template

test-clang-6:
  extends:
    - .test-clang
    - .clang6-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-clang-6
  except:
    variables:
      - $GROMACS_RELEASE

test-clang-7:
  extends:
    - .test-clang
    - .clang7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-clang-7
  except:
    variables:
      - $GROMACS_RELEASE

test-clang-7-release:
  extends:
    - .test-clang
    - .clang7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-release
      artifacts: true
    - job: build-clang-7-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-clang-7-gmxapi:
  extends:
    - .test-clang
    - .gmxapi-extra-installs
    - .clang7-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-clang-7-gmxapi
  except:
    variables:
      - $GROMACS_RELEASE

test-clang-7-gmxapi-release:
  extends:
    - .test-clang
    - .gmxapi-extra-installs
    - .clang7-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-7-gmxapi-release
      artifacts: true
    - job: build-clang-7-gmxapi-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE

test-clang-8:
  extends:
    - .test-clang
    - .clang8-template
  needs:
    - job: simple-build
      artifacts: false
    - job: build-clang-8
  except:
    variables:
      - $GROMACS_RELEASE

test-clang-8-release:
  extends:
    - .test-clang
    - .clang8-template
  stage: release-tests
  variables:
    BUILD_DIR: release-builds-clang
  needs:
    - job: configure-clang-8-release
      artifacts: true
    - job: build-clang-8-release
      artifacts: true
  only:
    refs:
      - triggers
      - web
      - schedules
    variables:
      - $GROMACS_RELEASE
